name: habitus_faith
description: App para llevar hábitos sanos + fortalecer tu fe día a día.
version: 1.1.19+28

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  uuid: ^4.5.3
  lottie: ^3.3.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^7.2.2
  shared_preferences: ^2.5.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  firebase_messaging: ^15.2.10
  flutter_timezone: ^3.0.1
  permission_handler: ^11.4.0
  tflite_flutter: ^0.12.1
  http: ^1.6.0
  workmanager: ^0.8.0
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  synchronized: ^3.4.0
  logger: ^2.6.2
  fl_chart: ^0.69.2
  signature: ^5.5.0
  table_calendar: ^3.2.0
  string_similarity: ^2.1.1
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.10
  firebase_remote_config: ^5.5.0
  google_fonts: ^6.3.2
  upgrader: ^8.4.0
  package_info_plus: ^4.2.0
  url_launcher: ^6.3.2
  collection: ^1.19.1

dev_dependencies:
  flutter_test:


    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.5.4
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  coverage: ^1.15.0
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  envied_generator: ^1.1.1
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/lottie/pets/
    - assets/biblia/
    - assets/ml_models/predictor.tflite
    - assets/ml_models/scaler_params.json
    - assets/ml_models/model_metadata.json
    - .env
    - assets/icons/app_icon.png
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
