// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// ============================================================================
// IMPORTANT: This file should be regenerated using FlutterFire CLI
// ============================================================================
//
// To properly configure Firebase for all platforms:
//
// 1. Install FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//
// 2. Run the configuration command:
//    flutterfire configure
//
// This will:
//   - Create/update google-services.json for Android (in android/app/)
//   - Create/update GoogleService-Info.plist for iOS/macOS (in ios/Runner/)
//   - Regenerate this file with correct API keys for all platforms
//
// SECURITY NOTES:
//   - google-services.json and GoogleService-Info.plist are already in .gitignore
//   - This file (firebase_options.dart) should also be in .gitignore for production
//   - For CI/CD, store config files as encrypted secrets
//
// For more information:
// https://firebase.google.com/docs/flutter/setup
//
// ============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import firebase_options.dart;
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual values by running: flutterfire configure
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_WEB_API_KEY',
    appId: '1:512385927943:web:REPLACE_WITH_ACTUAL_APP_ID',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    authDomain: 'habitus-faith-app.firebaseapp.com',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  // TODO: Replace with actual values by running: flutterfire configure
  // Note: Android primarily uses google-services.json, but these values are used as fallback
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_ANDROID_API_KEY',
    appId: '1:512385927943:android:c2daf83604d445feca53a2',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  // TODO: Replace with actual values by running: flutterfire configure
  // Note: iOS primarily uses GoogleService-Info.plist, but these values are used as fallback
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_IOS_API_KEY',
    appId: '1:512385927943:ios:REPLACE_WITH_ACTUAL_APP_ID',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );

  // TODO: Replace with actual values by running: flutterfire configure
  // Note: macOS primarily uses GoogleService-Info.plist, but these values are used as fallback
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_MACOS_API_KEY',
    appId: '1:512385927943:ios:REPLACE_WITH_ACTUAL_APP_ID',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );
}
