// File generated by FlutterFire CLI.
// This file contains Firebase configuration for the app.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iKq2eI-0zKxFP5N-VJJxn2YxSmK_g0I',
    appId: '1:512385927943:web:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    authDomain: 'habitus-faith-app.firebaseapp.com',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iKq2eI-0zKxFP5N-VJJxn2YxSmK_g0I',
    appId: '1:512385927943:android:c2daf83604d445feca53a2',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iKq2eI-0zKxFP5N-VJJxn2YxSmK_g0I',
    appId: '1:512385927943:ios:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1iKq2eI-0zKxFP5N-VJJxn2YxSmK_g0I',
    appId: '1:512385927943:ios:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );
}
