// File generated by FlutterFire CLI.
// This file contains Firebase configuration for the app.
//
// SECURITY WARNING: API keys have been removed from this file.
//
// To configure Firebase properly:
// 1. For Android: Download google-services.json from Firebase Console and place in android/app/
// 2. For iOS/macOS: Download GoogleService-Info.plist from Firebase Console and place in ios/Runner/
// 3. For Web: Replace 'YOUR_WEB_API_KEY' with your actual key OR use environment variables
// 4. Run: flutterfire configure (recommended) to regenerate this file automatically
//
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Replace with your Firebase Web API key
    appId: '1:512385927943:web:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    authDomain: 'habitus-faith-app.firebaseapp.com',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Replace with your Firebase Android API key or use google-services.json
    appId: '1:512385927943:android:c2daf83604d445feca53a2',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with your Firebase iOS API key or use GoogleService-Info.plist
    appId: '1:512385927943:ios:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with your Firebase macOS API key or use GoogleService-Info.plist
    appId: '1:512385927943:ios:PLACEHOLDER',
    messagingSenderId: '512385927943',
    projectId: 'habitus-faith-app',
    storageBucket: 'habitus-faith-app.firebasestorage.app',
    iosBundleId: 'com.develop4God.habitusFaith',
  );
}
