# habit_catalog.py
# Base catalog of 45 habits with metadata for scoring engine
# Language-agnostic: uses keys for i18n translation

HABIT_CATALOG = {
    "spiritual": [
        {
            "id": "sp01",
            "nameKey": "morning_prayer",
            "category": "spiritual",
            "emoji": "🙏",
            "base_duration": 10,
            "maturity_multiplier": {
                "new": 0.5,
                "growing": 1.0,
                "mature": 1.5,
                "passionate": 3.0
            },
            "tags": ["prayer", "morning", "foundational"],
            "motivation_match": ["closerToGod", "prayerDiscipline"],
            "challenge_fit": {
                "lackOfTime": 0.9,
                "lackOfMotivation": 0.8,
                "dontKnowStart": 1.0,
                "givingUp": 0.7
            },
            "support_boost": {"weak": 1.2},
            "verse_key": "psalms_5_3",
            "priority": 100,
            "time_of_day": "morning"
        },
        {
            "id": "sp02",
            "nameKey": "bible_reading",
            "category": "spiritual",
            "emoji": "📖",
            "base_duration": 15,
            "maturity_multiplier": {"new": 0.5, "growing": 1.0, "mature": 2.0, "passionate": 3.0},
            "tags": ["bible", "reading", "foundational"],
            "motivation_match": ["understandBible", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.7, "dontKnowStart": 0.9, "givingUp": 0.8},
            "support_boost": {"weak": 1.1},
            "verse_key": "psalms_119_105",
            "priority": 95,
            "time_of_day": "morning"
        },
        {
            "id": "sp03",
            "nameKey": "evening_prayer",
            "category": "spiritual",
            "emoji": "🌙",
            "base_duration": 10,
            "maturity_multiplier": {"new": 0.5, "growing": 1.0, "mature": 1.5, "passionate": 2.5},
            "tags": ["prayer", "evening", "reflection"],
            "motivation_match": ["closerToGod", "prayerDiscipline"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.9, "dontKnowStart": 1.0, "givingUp": 0.8},
            "support_boost": {"weak": 1.2},
            "verse_key": "psalms_4_8",
            "priority": 90,
            "time_of_day": "evening"
        },
        {
            "id": "sp04",
            "nameKey": "worship_music",
            "category": "spiritual",
            "emoji": "🎵",
            "base_duration": 15,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["worship", "music", "praise"],
            "motivation_match": ["closerToGod", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 1.0, "dontKnowStart": 0.9, "givingUp": 0.9},
            "priority": 85,
            "time_of_day": "flexible"
        },
        {
            "id": "sp05",
            "nameKey": "gratitude_journal",
            "category": "spiritual",
            "emoji": "✍️",
            "base_duration": 10,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["gratitude", "journaling", "reflection"],
            "motivation_match": ["closerToGod", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "verse_key": "1_thessalonians_5_18",
            "priority": 80,
            "time_of_day": "evening"
        },
        {
            "id": "sp06",
            "nameKey": "scripture_meditation",
            "category": "spiritual",
            "emoji": "📿",
            "base_duration": 15,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 2.0, "passionate": 3.0},
            "tags": ["meditation", "scripture", "contemplation"],
            "motivation_match": ["understandBible", "closerToGod"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.6, "dontKnowStart": 0.7, "givingUp": 0.6},
            "verse_key": "joshua_1_8",
            "priority": 75,
            "time_of_day": "morning"
        },
        {
            "id": "sp07",
            "nameKey": "fasting",
            "category": "spiritual",
            "emoji": "🍽️",
            "base_duration": 60,
            "maturity_multiplier": {"new": 0.3, "growing": 0.7, "mature": 1.0, "passionate": 1.5},
            "tags": ["fasting", "discipline", "sacrifice"],
            "motivation_match": ["prayerDiscipline", "overcomeHabits"],
            "challenge_fit": {"lackOfTime": 1.0, "lackOfMotivation": 0.5, "dontKnowStart": 0.6, "givingUp": 0.4},
            "verse_key": "matthew_6_16",
            "priority": 70,
            "time_of_day": "flexible"
        },
        {
            "id": "sp08",
            "nameKey": "serve_others",
            "category": "spiritual",
            "emoji": "🤝",
            "base_duration": 30,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["service", "compassion", "outreach"],
            "motivation_match": ["growInFaith", "closerToGod"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.8, "dontKnowStart": 0.7, "givingUp": 0.8},
            "verse_key": "matthew_25_40",
            "priority": 85,
            "time_of_day": "flexible"
        },
        {
            "id": "sp09",
            "nameKey": "bible_study_group",
            "category": "spiritual",
            "emoji": "👥",
            "base_duration": 60,
            "maturity_multiplier": {"new": 0.5, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["community", "study", "fellowship"],
            "motivation_match": ["understandBible", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.5, "lackOfMotivation": 0.9, "dontKnowStart": 0.8, "givingUp": 0.9},
            "support_boost": {"weak": 1.5},
            "verse_key": "hebrews_10_25",
            "priority": 80,
            "time_of_day": "evening"
        },
        {
            "id": "sp10",
            "nameKey": "prayer_walk",
            "category": "spiritual",
            "emoji": "🚶‍♂️",
            "base_duration": 20,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["prayer", "nature", "reflection"],
            "motivation_match": ["closerToGod", "prayerDiscipline"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.9, "dontKnowStart": 0.9, "givingUp": 0.8},
            "verse_key": "psalms_23_1",
            "priority": 75,
            "time_of_day": "morning"
        },
        {
            "id": "sp11",
            "nameKey": "scripture_memorization",
            "category": "spiritual",
            "emoji": "🧠",
            "base_duration": 10,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["memorization", "scripture", "discipline"],
            "motivation_match": ["understandBible", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.6, "dontKnowStart": 0.7, "givingUp": 0.6},
            "verse_key": "psalms_119_11",
            "priority": 70,
            "time_of_day": "morning"
        },
        {
            "id": "sp12",
            "nameKey": "intercessory_prayer",
            "category": "spiritual",
            "emoji": "🙌",
            "base_duration": 15,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 2.0, "passionate": 3.0},
            "tags": ["prayer", "intercession", "others"],
            "motivation_match": ["prayerDiscipline", "closerToGod"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "verse_key": "1_timothy_2_1",
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "sp13",
            "nameKey": "devotional_reading",
            "category": "spiritual",
            "emoji": "📚",
            "base_duration": 10,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["devotional", "reading", "inspiration"],
            "motivation_match": ["growInFaith", "understandBible"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.8, "dontKnowStart": 1.0, "givingUp": 0.8},
            "priority": 85,
            "time_of_day": "morning"
        },
        {
            "id": "sp14",
            "nameKey": "confession_repentance",
            "category": "spiritual",
            "emoji": "💔",
            "base_duration": 10,
            "maturity_multiplier": {"new": 0.5, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["confession", "repentance", "healing"],
            "motivation_match": ["overcomeHabits", "closerToGod"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.7, "dontKnowStart": 0.7, "givingUp": 0.8},
            "verse_key": "1_john_1_9",
            "priority": 70,
            "time_of_day": "evening"
        },
        {
            "id": "sp15",
            "nameKey": "praise_thanksgiving",
            "category": "spiritual",
            "emoji": "🎉",
            "base_duration": 10,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["praise", "thanksgiving", "joy"],
            "motivation_match": ["closerToGod", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.9, "lackOfMotivation": 0.9, "dontKnowStart": 1.0, "givingUp": 0.9},
            "verse_key": "psalms_100_4",
            "priority": 80,
            "time_of_day": "flexible"
        },
        {
            "id": "sp16",
            "nameKey": "sabbath_rest",
            "category": "spiritual",
            "emoji": "🛋️",
            "base_duration": 120,
            "maturity_multiplier": {"new": 0.5, "growing": 1.0, "mature": 1.0, "passionate": 1.5},
            "tags": ["sabbath", "rest", "renewal"],
            "motivation_match": ["closerToGod", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.4, "lackOfMotivation": 0.8, "dontKnowStart": 0.7, "givingUp": 0.7},
            "verse_key": "exodus_20_8",
            "priority": 65,
            "time_of_day": "flexible"
        },
        {
            "id": "sp17",
            "nameKey": "digital_detox_prayer",
            "category": "spiritual",
            "emoji": "📵",
            "base_duration": 30,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["detox", "focus", "silence"],
            "motivation_match": ["closerToGod", "overcomeHabits"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.6},
            "priority": 70,
            "time_of_day": "flexible"
        },
        {
            "id": "sp18",
            "nameKey": "christian_podcast",
            "category": "spiritual",
            "emoji": "🎧",
            "base_duration": 20,
            "maturity_multiplier": {"new": 1.0, "growing": 1.0, "mature": 1.0, "passionate": 1.5},
            "tags": ["teaching", "learning", "inspiration"],
            "motivation_match": ["understandBible", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.9, "dontKnowStart": 1.0, "givingUp": 0.8},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "sp19",
            "nameKey": "family_devotion",
            "category": "spiritual",
            "emoji": "👨‍👩‍👧‍👦",
            "base_duration": 20,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 1.5, "passionate": 2.0},
            "tags": ["family", "discipleship", "together"],
            "motivation_match": ["growInFaith", "closerToGod"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.8, "dontKnowStart": 0.8, "givingUp": 0.9},
            "support_boost": {"weak": 1.3},
            "verse_key": "deuteronomy_6_7",
            "priority": 75,
            "time_of_day": "evening"
        },
        {
            "id": "sp20",
            "nameKey": "spiritual_reading",
            "category": "spiritual",
            "emoji": "📖",
            "base_duration": 20,
            "maturity_multiplier": {"new": 0.7, "growing": 1.0, "mature": 1.5, "passionate": 2.5},
            "tags": ["reading", "theology", "growth"],
            "motivation_match": ["understandBible", "growInFaith"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "priority": 70,
            "time_of_day": "flexible"
        }
    ],
    "physical": [
        {
            "id": "ph01",
            "nameKey": "daily_walk",
            "category": "physical",
            "emoji": "🚶",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["exercise", "outdoor", "cardio"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.6, "dontKnowStart": 0.9, "givingUp": 0.9},
            "priority": 90,
            "time_of_day": "morning"
        },
        {
            "id": "ph02",
            "nameKey": "morning_exercise",
            "category": "physical",
            "emoji": "💪",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["exercise", "strength", "routine"],
            "motivation_match": ["physicalHealth", "productivity"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "priority": 85,
            "time_of_day": "morning"
        },
        {
            "id": "ph03",
            "nameKey": "yoga_stretching",
            "category": "physical",
            "emoji": "🧘",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["flexibility", "mindfulness", "wellness"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.7, "dontKnowStart": 0.9, "givingUp": 0.8},
            "priority": 80,
            "time_of_day": "morning"
        },
        {
            "id": "ph04",
            "nameKey": "healthy_breakfast",
            "category": "physical",
            "emoji": "🥗",
            "base_duration": 15,
            "maturity_multiplier": None,
            "tags": ["nutrition", "health", "routine"],
            "motivation_match": ["physicalHealth", "productivity"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.8, "dontKnowStart": 0.9, "givingUp": 0.8},
            "priority": 85,
            "time_of_day": "morning"
        },
        {
            "id": "ph05",
            "nameKey": "hydration_routine",
            "category": "physical",
            "emoji": "💧",
            "base_duration": 5,
            "maturity_multiplier": None,
            "tags": ["health", "hydration", "simple"],
            "motivation_match": ["physicalHealth"],
            "challenge_fit": {"lackOfTime": 1.0, "lackOfMotivation": 0.9, "dontKnowStart": 1.0, "givingUp": 0.9},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "ph06",
            "nameKey": "running_jogging",
            "category": "physical",
            "emoji": "🏃",
            "base_duration": 25,
            "maturity_multiplier": None,
            "tags": ["cardio", "running", "outdoor"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.6, "dontKnowStart": 0.7, "givingUp": 0.7},
            "priority": 80,
            "time_of_day": "morning"
        },
        {
            "id": "ph07",
            "nameKey": "strength_training",
            "category": "physical",
            "emoji": "🏋️",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["strength", "gym", "muscle"],
            "motivation_match": ["physicalHealth"],
            "challenge_fit": {"lackOfTime": 0.5, "lackOfMotivation": 0.7, "dontKnowStart": 0.7, "givingUp": 0.6},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "ph08",
            "nameKey": "bike_cycling",
            "category": "physical",
            "emoji": "🚴",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["cardio", "outdoor", "cycling"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "ph09",
            "nameKey": "healthy_meal_prep",
            "category": "physical",
            "emoji": "🍱",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["nutrition", "planning", "health"],
            "motivation_match": ["physicalHealth", "timeManagement"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "priority": 70,
            "time_of_day": "evening"
        },
        {
            "id": "ph10",
            "nameKey": "swimming",
            "category": "physical",
            "emoji": "🏊",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["cardio", "water", "full-body"],
            "motivation_match": ["physicalHealth"],
            "challenge_fit": {"lackOfTime": 0.5, "lackOfMotivation": 0.7, "dontKnowStart": 0.6, "givingUp": 0.7},
            "priority": 70,
            "time_of_day": "flexible"
        },
        {
            "id": "ph11",
            "nameKey": "dance_movement",
            "category": "physical",
            "emoji": "💃",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["cardio", "fun", "creative"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.9, "dontKnowStart": 0.8, "givingUp": 0.8},
            "priority": 70,
            "time_of_day": "flexible"
        },
        {
            "id": "ph12",
            "nameKey": "sports_recreation",
            "category": "physical",
            "emoji": "⚽",
            "base_duration": 45,
            "maturity_multiplier": None,
            "tags": ["sports", "social", "fun"],
            "motivation_match": ["physicalHealth"],
            "challenge_fit": {"lackOfTime": 0.5, "lackOfMotivation": 0.8, "dontKnowStart": 0.7, "givingUp": 0.8},
            "priority": 65,
            "time_of_day": "flexible"
        },
        {
            "id": "ph13",
            "nameKey": "posture_breaks",
            "category": "physical",
            "emoji": "🪑",
            "base_duration": 5,
            "maturity_multiplier": None,
            "tags": ["health", "ergonomics", "breaks"],
            "motivation_match": ["physicalHealth", "productivity"],
            "challenge_fit": {"lackOfTime": 1.0, "lackOfMotivation": 0.8, "dontKnowStart": 1.0, "givingUp": 0.9},
            "priority": 65,
            "time_of_day": "flexible"
        },
        {
            "id": "ph14",
            "nameKey": "outdoor_nature",
            "category": "physical",
            "emoji": "🌳",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["nature", "outdoor", "wellness"],
            "motivation_match": ["physicalHealth", "reduceStress"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.8, "dontKnowStart": 0.9, "givingUp": 0.8},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "ph15",
            "nameKey": "evening_walk",
            "category": "physical",
            "emoji": "🌆",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["exercise", "relaxation", "routine"],
            "motivation_match": ["physicalHealth", "reduceStress", "betterSleep"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.8, "dontKnowStart": 0.9, "givingUp": 0.9},
            "priority": 80,
            "time_of_day": "evening"
        }
    ],
    "mental": [
        {
            "id": "mn01",
            "nameKey": "mindfulness_meditation",
            "category": "mental",
            "emoji": "🧘",
            "base_duration": 10,
            "maturity_multiplier": None,
            "tags": ["mindfulness", "meditation", "stress"],
            "motivation_match": ["reduceStress"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.6, "dontKnowStart": 0.8, "givingUp": 0.8},
            "priority": 90,
            "time_of_day": "morning"
        },
        {
            "id": "mn02",
            "nameKey": "journaling",
            "category": "mental",
            "emoji": "📝",
            "base_duration": 15,
            "maturity_multiplier": None,
            "tags": ["reflection", "writing", "clarity"],
            "motivation_match": ["reduceStress", "productivity"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.7, "dontKnowStart": 0.9, "givingUp": 0.7},
            "priority": 85,
            "time_of_day": "evening"
        },
        {
            "id": "mn03",
            "nameKey": "deep_work_focus",
            "category": "mental",
            "emoji": "🎯",
            "base_duration": 45,
            "maturity_multiplier": None,
            "tags": ["productivity", "focus", "work"],
            "motivation_match": ["productivity", "timeManagement"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.7, "dontKnowStart": 0.8, "givingUp": 0.7},
            "priority": 85,
            "time_of_day": "morning"
        },
        {
            "id": "mn04",
            "nameKey": "reading_learning",
            "category": "mental",
            "emoji": "📚",
            "base_duration": 20,
            "maturity_multiplier": None,
            "tags": ["learning", "reading", "growth"],
            "motivation_match": ["productivity"],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.8, "dontKnowStart": 0.9, "givingUp": 0.8},
            "priority": 75,
            "time_of_day": "flexible"
        },
        {
            "id": "mn05",
            "nameKey": "digital_detox",
            "category": "mental",
            "emoji": "📵",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["detox", "mindfulness", "boundaries"],
            "motivation_match": ["reduceStress", "betterSleep"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.6, "dontKnowStart": 0.8, "givingUp": 0.6},
            "priority": 80,
            "time_of_day": "evening"
        },
        {
            "id": "mn06",
            "nameKey": "planning_review",
            "category": "mental",
            "emoji": "📅",
            "base_duration": 15,
            "maturity_multiplier": None,
            "tags": ["planning", "organization", "productivity"],
            "motivation_match": ["timeManagement", "productivity"],
            "challenge_fit": {"lackOfTime": 0.8, "lackOfMotivation": 0.7, "dontKnowStart": 0.9, "givingUp": 0.8},
            "priority": 85,
            "time_of_day": "evening"
        },
        {
            "id": "mn07",
            "nameKey": "breathing_exercises",
            "category": "mental",
            "emoji": "🌬️",
            "base_duration": 5,
            "maturity_multiplier": None,
            "tags": ["breathing", "calm", "stress"],
            "motivation_match": ["reduceStress"],
            "challenge_fit": {"lackOfTime": 1.0, "lackOfMotivation": 0.8, "dontKnowStart": 1.0, "givingUp": 0.9},
            "priority": 80,
            "time_of_day": "flexible"
        },
        {
            "id": "mn08",
            "nameKey": "creative_hobby",
            "category": "mental",
            "emoji": "🎨",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["creativity", "hobby", "relaxation"],
            "motivation_match": ["reduceStress"],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.8, "dontKnowStart": 0.7, "givingUp": 0.8},
            "priority": 70,
            "time_of_day": "flexible"
        }
    ],
    "relational": [
        {
            "id": "rl01",
            "nameKey": "call_friend_family",
            "category": "relational",
            "emoji": "📞",
            "base_duration": 15,
            "maturity_multiplier": None,
            "tags": ["connection", "support", "communication"],
            "motivation_match": [],
            "challenge_fit": {"lackOfTime": 0.7, "lackOfMotivation": 0.8, "dontKnowStart": 0.8, "givingUp": 0.9},
            "support_boost": {"weak": 2.0},
            "priority": 60,
            "time_of_day": "evening"
        },
        {
            "id": "rl02",
            "nameKey": "quality_time_loved_ones",
            "category": "relational",
            "emoji": "❤️",
            "base_duration": 30,
            "maturity_multiplier": None,
            "tags": ["connection", "family", "relationships"],
            "motivation_match": [],
            "challenge_fit": {"lackOfTime": 0.6, "lackOfMotivation": 0.9, "dontKnowStart": 0.9, "givingUp": 0.9},
            "support_boost": {"weak": 1.8},
            "priority": 65,
            "time_of_day": "evening"
        }
    ]
}

def get_all_habits():
    """Returns all 45 habits as a flat list"""
    all_habits = []
    for category in HABIT_CATALOG.values():
        all_habits.extend(category)
    return all_habits

def get_habits_for_intent(intent):
    """Returns appropriate habit pool based on user intent"""
    if intent == "faithBased":
        return HABIT_CATALOG["spiritual"]
    elif intent == "wellness":
        return (HABIT_CATALOG["physical"] +
                HABIT_CATALOG["mental"] +
                HABIT_CATALOG["relational"])
    else:  # both
        return get_all_habits()
